[project]
name = "gen-ai-fundamentals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "groq>=1.0.0",
    "ipywidgets>=8.1.8",
    "numpy>=2.4.2",
    "openai>=2.15.0",
    "qdrant-client>=1.17.1",
    "sentence-transformers>=5.2.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
